### ISSUE TITLE
0.3.0 introduced "TypeError: __init__() got an unexpected keyword argument 'sort'"

### ISSUE THREAD

**Issue by kalebdfischer** [flywheel-apps/GRP-5-transfer-log-report#23]
@hkethi002  0.3.0 introduced "TypeError: __init__() got an unexpected keyword argument 'sort'" (see attached)
[5dcd1d13c01312003964b270_logs.txt](https://github.com/flywheel-apps/GRP-5-transfer-log-report/files/3846643/5dcd1d13c01312003964b270_logs.txt)

Looks like previous version of GRP-5 were broken by an infrastructure change so the customer is effectively blocked.

**Comment by lmperry** [comment]
Solved by #25
